BASE_TASK_CONFIG_PATH: "configs/pose_estimation/mp3d_test_config.yaml"
TRAINER:
  TRAINER_NAME: "ppo"
  RL:
    PPO:
      # general options
      num_processes: 1
      task_config: "configs/pose_estimation/mp3d_test_config.yaml"
      sensors: "RGB_SENSOR,DEPTH_SENSOR,FINE_OCC_SENSOR,COARSE_OCC_SENSOR"
