ENVIRONMENT:
  MAX_EPISODE_STEPS: 501
SIMULATOR:
  TYPE: "Sim-v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'FINE_OCC_SENSOR', 'COARSE_OCC_SENSOR']
  ACTION_SPACE_CONFIG: "v2"
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  DEPTH_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  OCCUPANCY_MAPS:
    MAP_SCALE: 0.05
    MAP_SIZE: 800
    MAX_DEPTH: 3
    SMALL_MAP_RANGE: 40
    LARGE_MAP_RANGE: 200
    HEIGHT_LOWER: 0.5
    HEIGHT_UPPER: 2.0
  FINE_OCC_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  COARSE_OCC_SENSOR:
    WIDTH: 400
    HEIGHT: 400
TASK:
  TYPE: Pose-v0
  SENSORS: ['POSE_RGB_SENSOR', 'POSE_REGRESS_SENSOR', 'DELTA_SENSOR', 'ORACLE_ACTION_SENSOR']
  POSE_RGB_SENSOR:
    NREF: 20
  POSE_REGRESS_SENSOR:
    NREF: 20
  ORACLE_ACTION_SENSOR:
    ORACLE_TYPE: 'random'
  MEASUREMENTS: ['OPSR', 'AREA_COVERED', 'INC_AREA_COVERED', 'TOP_DOWN_MAP_POSE']
  OPSR:
    TYPE: OPSR
  TOP_DOWN_MAP_POSE:
    TYPE: TopDownMapPose
DATASET:
  TYPE: PoseEstimation-v1
  SPLIT: val
  DATA_PATH: data/datasets/pose_estimation/mp3d/v1_unique/{split}/{split}.json.gz
