BASE_TASK_CONFIG_PATH: "configs/reconstruction_exploration/mp3d_val_config.yaml"
TRAINER:
  TRAINER_NAME: "ppo"
  RL:
    PPO:
      # general options
      num_processes: 1
      task_config: "configs/reconstruction_exploration/mp3d_val_config.yaml"
      sensors: "RGB_SENSOR,DEPTH_SENSOR,FINE_OCC_SENSOR,COARSE_OCC_SENSOR"
