ENVIRONMENT:
  MAX_EPISODE_STEPS: 201
SIMULATOR:
  TYPE: "Sim-v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'FINE_OCC_SENSOR', 'COARSE_OCC_SENSOR']
  ACTION_SPACE_CONFIG: "v2"
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  DEPTH_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  OCCUPANCY_MAPS:
    MAP_SCALE: 0.05
    MAP_SIZE: 800
    MAX_DEPTH: 3
    SMALL_MAP_RANGE: 40
    LARGE_MAP_RANGE: 200
    HEIGHT_LOWER: 0.2
    HEIGHT_UPPER: 1.5
    USE_GT_OCC_MAP: False
    MEASURE_NOISE_FREE_AREA: True
  FINE_OCC_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  COARSE_OCC_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  OBJECT_ANNOTATIONS:
    IS_AVAILABLE: True
    PATH: 'data/object_annotations/mp3d'
  ENABLE_ODOMETRY_NOISE: False
  ODOMETER_NOISE_SCALING: 0.2
TASK:
  TYPE: Pose-v0
  SENSORS: ['ORACLE_ACTION_SENSOR']
  ORACLE_ACTION_SENSOR:
    ORACLE_TYPE: 'random'
  MEASUREMENTS: ['TOP_DOWN_MAP_POSE', 'AREA_COVERED', 'OBJECTS_COVERED_GEOMETRIC', 'OPSR', 'NOVELTY_REWARD', 'COVERAGE_NOVELTY_REWARD']
  TOP_DOWN_MAP_POSE:
    TYPE: TopDownMapPose
    FOG_OF_WAR:
        DRAW: True
        FOV: 90
        VISIBILITY_DIST: 4.0
  OPSR:
    TYPE: OPSR
    GEODESIC_DIST_THRESH: 2.0 # Meters
    ANGULAR_DIST_THRESH: 20.0 # Degrees
DATASET:
  TYPE: PoseEstimation-v1
  SPLIT: test
  DATA_PATH: data/datasets/pose_estimation/mp3d/v1/{split}/{split}.json.gz
  SHUFFLE_DATASET: False
