ENVIRONMENT:
  MAX_EPISODE_STEPS: 700
  T_EXP: 500
  T_NAV: 200
SIMULATOR:
  TYPE: "Sim-v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'FINE_OCC_SENSOR', 'COARSE_OCC_SENSOR', 'HIGHRES_COARSE_OCC_SENSOR']
  ACTION_SPACE_CONFIG: "v2"
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 84
    HEIGHT: 84
  DEPTH_SENSOR:
    WIDTH: 84
    HEIGHT: 84
  OCCUPANCY_MAPS:
    MAP_SCALE: 0.05
    MAP_SIZE: 800
    MAX_DEPTH: 3
    SMALL_MAP_RANGE: 40
    LARGE_MAP_RANGE: 200
    HEIGHT_LOWER: 0.5
    HEIGHT_UPPER: 2.0
  FINE_OCC_SENSOR:
    WIDTH: 84
    HEIGHT: 84
  COARSE_OCC_SENSOR:
    WIDTH: 84
    HEIGHT: 84
  HIGHRES_COARSE_OCC_SENSOR:
    WIDTH: 800
    HEIGHT: 800
TASK:
  TYPE: ExpNav-v0
  SUCCESS_DISTANCE: 0.2
  SENSORS: ['ORACLE_ACTION_SENSOR', 'GRID_GOAL_SENSOR', 'SP_ACTION_SENSOR']
  ORACLE_ACTION_SENSOR:
    ORACLE_TYPE: 'random'
  GRID_GOAL_SENSOR:
    TYPE: GridGoalSensorExploreNavigation
    T_EXP: 500
    T_NAV: 200
  SP_ACTION_SENSOR:
    TYPE: SPActionSensorExploreNavigation
    T_EXP: 500
    T_NAV: 200
  MEASUREMENTS: ['TOP_DOWN_MAP_EXP_NAV']
  TOP_DOWN_MAP_EXP_NAV:
    T_EXP: 500
    T_NAV: 200
DATASET:
  TYPE: ExpNav-v1
  SPLIT: test
  DATA_PATH: <HABITAT_ROOT>/habitat-api/data/datasets/exp_nav/mp3d/v1/{split}/{split}.json.gz
  SHUFFLE_DATASET: False
