ENVIRONMENT:
  MAX_EPISODE_STEPS: 501
SIMULATOR:
  TYPE: "Sim-v1"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'FINE_OCC_SENSOR', 'COARSE_OCC_SENSOR']
  ACTION_SPACE_CONFIG: "v2"
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  DEPTH_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  OCCUPANCY_MAPS:
    MAP_SCALE: 0.05
    MAP_SIZE: 800
    MAX_DEPTH: 3
    SMALL_MAP_RANGE: 40
    LARGE_MAP_RANGE: 200
    HEIGHT_LOWER: 0.5
    HEIGHT_UPPER: 2.0
    USE_GT_OCC_MAP: True
  FINE_OCC_SENSOR:
    WIDTH: 400
    HEIGHT: 400
  COARSE_OCC_SENSOR:
    WIDTH: 400
    HEIGHT: 400
TASK:
  TYPE: Pose-v0
  SENSORS: ['POSE_RGB_SENSOR', 'POSE_REGRESS_SENSOR', 'ORACLE_ACTION_SENSOR']
  POSE_RGB_SENSOR:
    NREF: 100
  POSE_REGRESS_SENSOR:
    NREF: 100
  MEASUREMENTS: ['TOP_DOWN_MAP_POSE']
  TOP_DOWN_MAP_POSE:
    TYPE: TopDownMapPose
    FOG_OF_WAR:
        DRAW: True
        FOV: 90
        VISIBILITY_DIST: 4.0
DATASET:
  TYPE: PoseEstimation-v1
  SPLIT: test
  DATA_PATH: <HABITAT_ROOT>/habitat-api/data/datasets/uniform_pose_estimation/mp3d/v1/{split}/{split}.json.gz
  SHUFFLE_DATASET: False
