ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
  RGB_SENSOR:
    WIDTH: 84
    HEIGHT: 84
  DEPTH_SENSOR:
    WIDTH: 84
    HEIGHT: 84
TASK:
  TYPE: Nav-v0
  SUCCESS_DISTANCE: 0.2
  SENSORS: ['POINTGOAL_SENSOR']
  POINTGOAL_SENSOR:
    TYPE: PointGoalSensor
    GOAL_FORMAT: POLAR
  MEASUREMENTS: ['SPL']
  SPL:
    TYPE: SPL
    SUCCESS_DISTANCE: 0.2
DATASET:
  TYPE: PointNav-v1
  SPLIT: test
  DATA_PATH: data/datasets/pointnav/mp3d/v1_unique/{split}/{split}.json.gz
  SCENES_DIR: data/scene_datasets
  SHUFFLE_DATASET: False
